### ISSUE TITLE
 State: Instance of 'AppState'

### ISSUE THREAD

**Issue by aleksander351** [brianegan/redux_logging#11]
I would like to see the actual output of the AppState, i.e. my state object. But I get only this message:

 **State: Instance of 'AppState'**

**Comment by brianegan** [comment]
Hey there -- all Dart classes can implement the `toString` method, which determines how to convert the object into a String.

Therefore, please implement the `toString` method on your `AppState` class to return a String with the information you need. If you're using Android studio / IntelliJ, it can generate the toString method for ya!

**Comment by aleksander351** [comment]
Am I really the only one with this issue?
Does anyone have an example how to implement it?
I converted state.toString(), but the result is still the same.
I also restarted flutter to make sure.

I can not find any example how to solve this.

**Comment by brianegan** [comment]
Ah, my bad -- in this case, you don't need to call `toString`, you need to *implement* or *write* your own `toString` method for the State class.

You can see an example implementation here: https://github.com/brianegan/flutter_architecture_samples/blob/master/redux/lib/models/app_state.dart#L55

In this case, the `AppState` class implements the `toString` method to return the data contained within the Store. You can do the same, or print specific parts -- it's all up to you!

**Comment by aleksander351** [comment]
Damn, I saw this somewhere in a tutorial but I forgot where.
Vielen Dank! 👍 ;)
